### ISSUE TITLE
create-self-hosted-runner: automatically use the latest Git for Windows and GitHub Actions runner version

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git-for-windows-automation#16]
When spinning up the self-hosted Windows/ARM64 runners, we [hard-code the Git for Windows version](https://github.com/git-for-windows/git-for-windows-automation/blob/200fdc9be4b4af6dc8751f2e18202eeab9ff5253/azure-self-hosted-runners/post-deployment-script.ps1#L32-L34) that gets installed, and likewise we [hard-code the GitHub Actions runner version](https://github.com/git-for-windows/git-for-windows-automation/blob/200fdc9be4b4af6dc8751f2e18202eeab9ff5253/azure-self-hosted-runners/post-deployment-script.ps1#L36-L39).

Let's determine the latest versions of both components automatically.

This requires a little bit of PowerShell scripting, accessing https://api.github.com/repos/git-for-windows/git/releases/latest and https://api.github.com/repos/actions/runner/releases/latest. Both the version string as well as the SHA-256 checksums need to be parsed out of the response.

**Comment by hmartinez82** [comment]
Working on it

**Comment by hmartinez82** [comment]
I can't find a programmatic way of getting the checksum for the assets being downloaded. As per this discussion https://github.com/orgs/community/discussions/23512 it seems that it's a missing feature and it's up the the maintainers to list the asset checksums in the release notes. Any ideia?

**Comment by rimrul** [comment]
The checksums are listed in the release notes, so we should be able to parse them from there.

https://github.com/actions/runner/releases/latest

https://github.com/git-for-windows/git/releases/latest

**Comment by hmartinez82** [comment]
Oh boy. Ok, I'll try that approach tomorrow. I didn't expect we were going there 😅
 🤞🏼  they won't change the release notes format

**Comment by rimrul** [comment]
Certainly not ideal, but it's the best we've got

**Comment by rstolpe** [comment]
@dscho it do seem that @hmartinez82 has fixed this issue already, I was to slow. But if you have any other Powershell needs just DM me and I can look at it.

I can't see @hmartinez82 pull request but I guess that this one will close the issue :)

**Comment by rstolpe** [comment]
@dscho and @hmartinez82 I have a better solution for the Hash issue, hold on I'm looking in to it now.

**Comment by hmartinez82** [comment]
@rstolpe You mean https://github.com/git-for-windows/git-for-windows-automation/pull/19  ? I'll close mine. You have a better solution with error handling and all

**Comment by rstolpe** [comment]
This issue will be closed with #19 pull req.
