### ISSUE TITLE
`update-via-pacman.ps1` missing in `build-installers` artifact

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/git-for-windows-automation#97]
I tried to kick off [this workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/10929821802/job/30341364924) to build and publish the Pacman package for `mingw-w64-git` ARM64, but it failed with:

```
& : The term 'D:/git-sdk-arm64-build-installers\update-via-pacman.ps1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
```

Turns out the reason is this:
- There is [this](https://github.com/git-for-windows/git-for-windows-automation/blob/295d792782bb2774766a4ca4ae0639c793c7f1cc/.github/workflows/build-and-deploy.yml#L103) logic that uses the `build-installers` artifact _only_ when building `mingw-w64-git`, and otherwise `full` in all other cases;
- In `please.sh`, there is [this line](https://github.com/git-for-windows/build-extra/blob/76751073989fa261449a2cc94b8a5defbd8958a5/please.sh#L3242) which adds `update-via-pacman.ps1` to the list of files to include in the `build-installers` artifact, but that list then gets overwritten [here](https://github.com/git-for-windows/build-extra/blob/76751073989fa261449a2cc94b8a5defbd8958a5/please.sh#L3305) by the list from `.sparse/minimal-sdk` for any non-i686 artifact, then [enriched](https://github.com/git-for-windows/build-extra/blob/76751073989fa261449a2cc94b8a5defbd8958a5/please.sh#L3307) with the list from `.sparse/makepkg-git`. Both of these [do not include](https://github.com/git-for-windows/git-sdk-arm64/blob/main/.sparse/makepkg-git) `update-via-pacman.ps1`, so it doesn't end up in the final `build-installers` artifact.

There's three ways to solve this (in random order):
1. Update [this](https://github.com/git-for-windows/git-for-windows-automation/blob/295d792782bb2774766a4ca4ae0639c793c7f1cc/.github/workflows/build-and-deploy.yml#L103) logic to simply use the `full` Git for Windows SDK flavor at all times, removing the exception for `mingw-w64-git`;
2. Updating `please.sh` to not completely [overwrite](https://github.com/git-for-windows/build-extra/blob/76751073989fa261449a2cc94b8a5defbd8958a5/please.sh#L3305) the list of files that already included `update-via-pacman.ps1`, but only using `.sparse/minimal-sdk` and `.sparse/makepkg-git` to _enhance_ the base list;
3. Updating [`.sparse/makepkg-git`](https://github.com/git-for-windows/git-sdk-arm64/blob/e0fb2edee4af92917f4912796a9d9fa6e18cdc78/.sparse/makepkg-git) to simply include `update-via-pacman.ps1`.

Option 3 would be the fastest and easiest to implement, with very little risk involved of breaking other things. @dscho I'm curious if you have any thoughts on a preferred option to move forward with this. Thanks!

**Comment by dscho** [comment]
I like option 3! We specifically include `pacman` in that SDK artifact, after all.

**Comment by rimrul** [comment]
Yes, option 3 looks like the best choice.

We might want to revisit why we create a first list and then replace it, at some point in the future, though.

**Comment by dennisameling** [comment]
Option 3 it is, then! [Here's a PR](https://github.com/git-for-windows/git-sdk-arm64/pull/25).

> We might want to revisit why we create a first list and then replace it, at some point in the future, though.

I agree. Something to keep in mind!

**Comment by dennisameling** [comment]
Looks like we need two more files in order for `update-via-pacman.ps1` to succeed: https://github.com/git-for-windows/git-sdk-arm64/pull/26

**Comment by dennisameling** [comment]
It [worked](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/10929821802/job/30385950670) this time - exciting!

**Comment by dennisameling** [comment]
And the `git-sdk-arm64` has now been [updated](https://github.com/git-for-windows/git-sdk-arm64/commit/95fd42af9a791a7545eea4a4e4d6573c564a6b2f) from GfW 2.39.1 to 2.46.1 as well. Amazing!
